name: ISO Library Master Sync

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  sync-process:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Runner Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          docker-images: true

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure Rclone
        env:
          MY_RCLONE_CONF: ${{ secrets.RCLONE_CONF_DATA }}
        run: |
          mkdir -p ~/.config/rclone
          # ใช้ printf เพื่อรักษาฟอร์แมต JSON ให้คงเดิม 100%
          printf "%s" "$MY_RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Start Sync Script
        run: python3 sync_script.py
